name: Build & Test

# Triggers on pushes or pull requests to any branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
    - name: Check-out Repo # (under $GITHUB_WORKSPACE)
      uses: actions/checkout@v2 
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.805

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17

    - name: Install dependencies
      run: npm ci

    - name: Build & Run Tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: ./do build test --production
    
    - name: Create Package
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: ./do package --production

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '.obj/Rewrap-VSCode.vsix'
